### ISSUE TITLE
about zmk config

### ISSUE THREAD

**Issue by purefall0624** [SuperFola/arkenswoop#4]
Hello there! I have just ordered your attractive arkenswoop pcbs, i couldn't wait to use it. But there is something confuses me, I didn't find zmk config for arkenswoop, only for alkenswoop. Is the one for alkenswoop suits for arkenswoop? And is there any problem with the encoders? I'll be grateful for your response.

**Comment by SuperFola** [comment]
Hi there!

The altenswoop config will work with the arkenswoop, they are essentially identical, except for `Z` and `/` being moved to the side. The layout change is this one https://github.com/SuperFola/zmk-altenswoop/commit/a7ec5aa4e6beb7fb16a425348a43bc7a509d3e26, it only impacts what you see on https://nickcoutsos.github.io/keymap-editor/ with the keymap.

I'm happy to report the encoders work as expected, I will add a new commit tonight to fix the orientation of the right side encoder though (the pin are reversed in the config, making "turn left" being in fact a "turn right" action if that makes sense). Only thing I would have liked to figure out is the perfect resolution for the encoders: 1 is too low to my liking and 2 a tad bit too high

**Comment by purefall0624** [comment]
I have something to say about the resolution for the encoders. Have you checked out the latest blog of zmk? If so, maybe you will be happy to find out that zmk add 'step' to cotrol the encoder better. I hope that it would be of some help to you.https://zmk.dev/blog/2023/06/18/encoder-refactors

**Comment by SuperFola** [comment]
I saw that yesterday, it seems to be fixed now with 5 triggers per rotation and 15 steps (15 being the number of clicks you can get on an evqwgd001 doing a full rotation).

**Comment by dinhtungdu** [comment]
> The layout change is this one https://github.com/SuperFola/zmk-altenswoop/commit/a7ec5aa4e6beb7fb16a425348a43bc7a509d3e26, it only impacts what you see on [nickcoutsos.github.io/keymap-editor](https://nickcoutsos.github.io/keymap-editor/) with the keymap.

@SuperFola so should I revert the change in that commit to build firmware for arkenswoop or I can use `SuperFola/zmk-altenswoop` as it is and just add my keymap?

**Comment by SuperFola** [comment]
It will work, they are wired exactly the same way. You can revert that commit to get the correct orientation in the UI on zmk editor though.

**Comment by dinhtungdu** [comment]
> It will work, they are wired exactly the same way.

Ah, this explains! I get it now. Thank you so much!
