### ISSUE TITLE
about building zmk firmware

### ISSUE THREAD

**Issue by purefall0624** [SuperFola/arkenswoop#6]
Hi there!
Sorry to trouble but there is something wrong with the building of the zmk firmware. You can try it and the error is as followed:
 it says 'Found west (found suitable version "1.2.0", minimum required is "0.14.0") 
Found Dtc: /opt/zephyr-sdk-0.16.3/sysroots/x86_64-pokysdk-linux/usr/bin/dtc (found suitable version "1.6.0", minimum required is "1.4.6") '
it seems like something's version is too old for the action to be conducted.
Anyway, it will be so kindful of you if you can handle this issue. :) i really love your work for the kbd

**Comment by SuperFola** [comment]
Hi there,

As a temporary fix because I don't have the time nor resources I have locked the zmk version to 331915f98931308f49f43485c75f5d0c08f0cf29 on SuperFola/zmk-altenswoop (as of january 14th, 2024)
